# Generated by Django 6.0.1 on 2026-03-05 15:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(verbose_name='Giá bán')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Link ảnh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Tọa độ cửa hàng')),
            ],
        ),
    ]
