# Generated by Django 6.0.1 on 2026-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_desc_image_url_product_image_url_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Điện thoại, Tablet'), ('ipad', 'iPad, Máy tính bảng'), ('laptop', 'Laptop, Macbook'), ('am-thanh', 'Âm thanh, Tai nghe'), ('phu-kien', 'Phụ kiện công nghệ')], default='phone', max_length=50),
        ),
    ]
