# Generated by Django 6.0.1 on 2026-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Điện thoại'), ('laptop', 'Laptop'), ('ipad', 'Máy tính bảng'), ('am-thanh', 'Âm thanh'), ('phu-kien', 'Phụ kiện')], default='phone', max_length=50, verbose_name='Loại sản phẩm'),
        ),
    ]
