# Generated by Django 6.0.1 on 2026-04-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
