# Generated by Django 6.0.1 on 2026-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thương hiệu (VD: Apple, Samsung...)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Điện thoại, Tablet'), ('laptop', 'Laptop, Macbook'), ('ipad', 'iPad, Máy tính bảng'), ('am-thanh', 'Âm thanh, Tai nghe'), ('phu-kien', 'Phụ kiện công nghệ')], default='phone', max_length=20, verbose_name='Loại sản phẩm'),
        ),
    ]
