# Generated by Django 6.0.1 on 2026-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Điện thoại, Tablet'), ('laptop', 'Laptop, Macbook'), ('ipad', 'iPad, Máy tính bảng'), ('am-thanh', 'Âm thanh, Tai nghe'), ('phu-kien', 'Phụ kiện công nghệ')], default='Điện thoại, Tablet', max_length=20, verbose_name='Loại sản phẩm'),
        ),
    ]
