# Generated by Django 6.0.1 on 2026-04-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_5',
        ),
        migrations.RemoveField(
            model_name='store',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='desc_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/desc/', verbose_name='Ảnh trong mô tả'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh chính'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh phụ 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh phụ 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh phụ 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh phụ 4'),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Ảnh cửa hàng'),
        ),
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Điện thoại, Tablet'), ('laptop', 'Laptop, Macbook'), ('ipad', 'iPad, Máy tính bảng'), ('am-thanh', 'Âm thanh, Tai nghe'), ('phu-kien', 'Phụ kiện công nghệ')], default='phone', max_length=20, verbose_name='Loại sản phẩm'),
        ),
    ]
