# Generated by Django 6.0.1 on 2026-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_assigned_store_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Ảnh Poster 2'),
        ),
        migrations.AddField(
            model_name='store',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Ảnh Poster 3'),
        ),
        migrations.AddField(
            model_name='store',
            name='promotion_text',
            field=models.TextField(blank=True, null=True, verbose_name='Chương trình ưu đãi'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Ảnh chính'),
        ),
    ]
