# Generated by Django 6.0.1 on 2026-04-15 01:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_store_manager_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='store',
            name='promotion_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Chương trình ưu đãi'),
        ),
    ]
