# Generated by Django 6.0.1 on 2026-05-02 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_about_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_main',
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề chính'),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_gallery/')),
                ('is_banner', models.BooleanField(default=False, verbose_name='Dùng làm Banner động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.about')),
            ],
        ),
    ]
