# Generated by Django 6.0.1 on 2026-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_about_banner_remove_about_image_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='is_banner',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image_type',
            field=models.CharField(choices=[('banner', 'Banner động'), ('story', 'Gallery câu chuyện')], default='story', max_length=10),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Câu chuyện thương hiệu'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Về ONEWAY STORE', max_length=200),
        ),
    ]
