# Generated by Django 6.0.1 on 2026-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_aboutimage_is_banner_aboutimage_image_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='image_type',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='Dùng làm Banner động'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề chính'),
        ),
    ]
