# Generated by Django 6.0.1 on 2026-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_aboutimage_image_type_aboutimage_is_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='is_banner',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('story', 'Câu chuyện')], default='story', max_length=10),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='slot_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Câu chuyện thương hiệu'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Về ONEWAY STORE', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to='about/'),
        ),
    ]
