# Generated by Django 6.0.1 on 2026-05-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_aboutimage_is_banner_aboutimage_image_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
