# Generated by Django 6.0.1 on 2026-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_aboutimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Giới thiệu Oneway Store', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('story', 'Story')], max_length=10),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='slot_number',
            field=models.IntegerField(),
        ),
    ]
