# Generated by Django 6.0.1 on 2026-05-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_companyinfo_remove_aboutimage_about_companyimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stores/gallery/', verbose_name='Ảnh Slide')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.store')),
            ],
        ),
    ]
