"""
Django settings for oneway project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
GDAL_LIBRARY_PATH =r"C:\Users\admn\AppData\Local\Programs\Python\Python313\Lib\site-packages\osgeo\gdal.dll"
os.environ["PATH"] += r";C:\Users\admn\AppData\Local\Programs\Python\Python313\Lib\site-packages\osgeo"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-medmfyzvq_0tfbxzy%r7347z2+$e116k+32za+7188v=5rnqb*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'django.contrib.gis', # Thêm dòng này để dùng các hàm bản đồ
    'leaflet', # THÊM DÒNG NÀY VÀO ĐÂY
    'django_user_agents',
    'ckeditor',
    'ckeditor_uploader',
]

CKEDITOR_UPLOAD_PATH = "uploads/editor/"

# Cấu hình thư mục lưu ảnh khi upload từ editor
CKEDITOR_UPLOAD_PATH = "uploads/editor/"

# Tùy chỉnh giao diện thanh công cụ giống ảnh ngài gửi
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format', 'Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['Link', 'Unlink'],
            ['Image'], # Nút chèn ảnh
            ['Maximize']
        ],
        'height': 300, # Chiều cao mặc định của khung nhập
        'width': '100%',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware'
]

ROOT_URLCONF = 'oneway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oneway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Sử dụng engine của PostGIS thay vì PostgreSQL bình thường
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'oneway_db',        # Tên database ngài vừa tạo
        'USER': 'postgres',         # User mặc định của PostgreSQL
        'PASSWORD': '123456',          # Mật khẩu lúc ngài cài PostgreSQL (Sửa lại cho đúng)
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Đường dẫn URL để truy cập ảnh trên web
MEDIA_URL = '/media/'

# Thư mục thực tế trên máy tính để chứa ảnh
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (10.762622, 106.660172), # Tọa độ TP.HCM
    'DEFAULT_ZOOM': 12,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
}
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'

# oneway/settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'uniconr546@gmail.com'
EMAIL_HOST_PASSWORD = 'arcu lcyo rjhu udpw' # Không phải mật khẩu đăng nhập

